"""Creacion Marca-Tipo

Revision ID: 09df915b5774
Revises: 
Create Date: 2024-06-18 23:06:57.295652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09df915b5774'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo')
    op.drop_table('marca')
    # ### end Alembic commands ###
