"""Relaciones VehiculoTipoMarca

Revision ID: 9a1b4824a5df
Revises: 
Create Date: 2024-07-02 20:22:17.698751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a1b4824a5df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cilindrada', sa.Integer(), nullable=True))
        batch_op.alter_column('modelo',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculo', schema=None) as batch_op:
        batch_op.alter_column('modelo',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('cilindrada')

    # ### end Alembic commands ###
